services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mormor
      POSTGRES_DB: PhoneB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/init.sql


  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: mormor
      DB_NAME: PhoneB
      REDIS_ADDR: redis:6379
      PORT: 8080
    depends_on:
      - db

volumes:
  pgdata:
